/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import oru.inf.InfDB;

/**
 *
 * @author Josanna, Linda & Lisa
 */
public class HanteraAliens extends javax.swing.JFrame {

    private InfDB idb;
    private String anvId;
    private String anvTyp;

    public HanteraAliens(InfDB idb, String anvId, String anvTyp) {
        initComponents();
        this.idb = idb;
        this.anvId = anvId;
        this.anvTyp = anvTyp;
        menuBarTomt.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAgentBild = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JToggleButton();
        btnListaPlats = new javax.swing.JButton();
        btnRegistreraNyAlien = new javax.swing.JButton();
        btnUppdatera = new javax.swing.JToggleButton();
        btnSok = new javax.swing.JToggleButton();
        btnListaAlienRas = new javax.swing.JToggleButton();
        btnListaAlienDatum = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        menuBarStartsida = new javax.swing.JMenu();
        menuBarInget = new javax.swing.JMenu();
        menuBarTomt = new javax.swing.JMenu();
        manuBarLoggaUt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAgentBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/BlueAlien.png"))); // NOI18N

        lblRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblRubrik.setText("Hantera aliens");

        btnTillbaka.setText("Gå tillbaka");
        btnTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTillbakaMouseClicked(evt);
            }
        });

        btnListaPlats.setText("Lista alien utifrån plats");
        btnListaPlats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaPlatsMouseClicked(evt);
            }
        });

        btnRegistreraNyAlien.setText("Registrera ny alien");
        btnRegistreraNyAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistreraNyAlienMouseClicked(evt);
            }
        });

        btnUppdatera.setText("Uppdatera alien");
        btnUppdatera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUppdateraMouseClicked(evt);
            }
        });

        btnSok.setText("Sök alien");
        btnSok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSokMouseClicked(evt);
            }
        });

        btnListaAlienRas.setText("Lista alien utifrån ras");
        btnListaAlienRas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaAlienRasMouseClicked(evt);
            }
        });

        btnListaAlienDatum.setText("Lista alien utifrån registreringsdatum");
        btnListaAlienDatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaAlienDatumMouseClicked(evt);
            }
        });

        menuBarStartsida.setText("Gå till Startsida");
        menuBarStartsida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarStartsidaMouseClicked(evt);
            }
        });
        menuBar.add(menuBarStartsida);

        menuBarInget.setText("                                                                                                        ");
        menuBar.add(menuBarInget);

        menuBarTomt.setText("Inloggad som Agent");
        menuBar.add(menuBarTomt);

        manuBarLoggaUt.setText("Logga ut");
        manuBarLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manuBarLoggaUtMouseClicked(evt);
            }
        });
        menuBar.add(manuBarLoggaUt);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListaAlienDatum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaAlienRas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaPlats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUppdatera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistreraNyAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(lblAgentBild, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(lblRubrik))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnTillbaka)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblAgentBild, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnRegistreraNyAlien)
                        .addGap(18, 18, 18)
                        .addComponent(btnUppdatera)
                        .addGap(18, 18, 18)
                        .addComponent(btnSok)
                        .addGap(18, 18, 18)
                        .addComponent(btnListaPlats)
                        .addGap(18, 18, 18)
                        .addComponent(btnListaAlienRas)
                        .addGap(18, 18, 18)
                        .addComponent(btnListaAlienDatum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)
                        .addGap(23, 23, 23))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metoden gör nuvarande fönster osynligt och öppnar klassen ListaAliensPlats i nytt fönster.
    private void btnListaPlatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaPlatsMouseClicked
        setVisible(false);
        ListaAliensPlats listaAlien = new ListaAliensPlats(idb, anvId, anvTyp);
        listaAlien.setVisible(true);
    }//GEN-LAST:event_btnListaPlatsMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen RegistreraAlien i nytt fönster.
    private void btnRegistreraNyAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistreraNyAlienMouseClicked
        setVisible(false);
        RegistreraAlien registreraAlien = new RegistreraAlien(idb, anvId, anvTyp);
        registreraAlien.setVisible(true);
    }//GEN-LAST:event_btnRegistreraNyAlienMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen UppdateraAlien i nytt fönster.
    private void btnUppdateraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUppdateraMouseClicked
        setVisible(false);
        UppdateraAlien uppdateraAlien = new UppdateraAlien(idb, anvId, anvTyp);
        uppdateraAlien.setVisible(true);
    }//GEN-LAST:event_btnUppdateraMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen SokAlien i nytt fönster.
    private void btnSokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSokMouseClicked
        setVisible(false);
        SokAlien sokAlien = new SokAlien(idb, anvId, anvTyp);
        sokAlien.setVisible(true);    }//GEN-LAST:event_btnSokMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen StartsidaAgent i nytt fönster.
    private void menuBarStartsidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarStartsidaMouseClicked
        setVisible(false);
        StartsidaAgent startsidaAgent = new StartsidaAgent(idb, anvId, anvTyp);
        startsidaAgent.setVisible(true);
    }//GEN-LAST:event_menuBarStartsidaMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen Inloggning i nytt fönster. En blir utloggad och kommer tillbaka till inloggningsfönstret.
    private void manuBarLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manuBarLoggaUtMouseClicked
        setVisible(false);
        Inloggning inlogg = new Inloggning(idb);
        inlogg.setVisible(true);
    }//GEN-LAST:event_manuBarLoggaUtMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen StartsidaAgent i nytt fönster.
    private void btnTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTillbakaMouseClicked
        setVisible(false);
        StartsidaAgent startsidaAgent = new StartsidaAgent(idb, anvId, anvTyp);
        startsidaAgent.setVisible(true);
    }//GEN-LAST:event_btnTillbakaMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen ListaAliensDatum i nytt fönster.
    private void btnListaAlienDatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAlienDatumMouseClicked
        setVisible(false);
        ListaAliensDatum datum = new ListaAliensDatum(idb, anvId, anvTyp);
        datum.setVisible(true);
    }//GEN-LAST:event_btnListaAlienDatumMouseClicked

    //Metoden gör nuvarande fönster osynligt och öppnar klassen SokListaAliensRas i nytt fönster.
    private void btnListaAlienRasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaAlienRasMouseClicked
        setVisible(false);
        ListaAliensRas ras = new ListaAliensRas(idb, anvId, anvTyp);
        ras.setVisible(true);
    }//GEN-LAST:event_btnListaAlienRasMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnListaAlienDatum;
    private javax.swing.JToggleButton btnListaAlienRas;
    private javax.swing.JButton btnListaPlats;
    private javax.swing.JButton btnRegistreraNyAlien;
    private javax.swing.JToggleButton btnSok;
    private javax.swing.JToggleButton btnTillbaka;
    private javax.swing.JToggleButton btnUppdatera;
    private javax.swing.JLabel lblAgentBild;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JMenu manuBarLoggaUt;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBarInget;
    private javax.swing.JMenu menuBarStartsida;
    private javax.swing.JMenu menuBarTomt;
    // End of variables declaration//GEN-END:variables
}
