/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author luna
 */
public class ListaAliensPlats extends javax.swing.JFrame {

    /**
     * Creates new form StartsidaAgent
     */
    private InfDB idb;
    private String anvId;
    private String anvTyp;
    
    
    public ListaAliensPlats(InfDB idb) {
        initComponents();
        this.idb = idb;
  
    }

    public ListaAliensPlats(InfDB idb, String anvId, String anvTyp) {
        initComponents();
        this.idb = idb;
        this.anvId = anvId;
        this.anvTyp = anvTyp;
        menuBarInloggadSom.setText("Inloggad som " + anvTyp);
        //Hämta alla områden så dom finns i Combobox från början
        getOmraden();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListaAliens = new javax.swing.JLabel();
        btnGaTillbaka = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTabell = new javax.swing.JTable();
        cmBoxOmrade = new javax.swing.JComboBox<>();
        lblFilterVal = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        cmBoxPlats = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuBarAndraLosen = new javax.swing.JMenuItem();
        menuBarHanteraAlien = new javax.swing.JMenu();
        menuBarRegNyAlien = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        menyBarListaPlats = new javax.swing.JMenuItem();
        menuBarListaRas = new javax.swing.JMenuItem();
        menuBarListaDatum = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuBarInloggadSom = new javax.swing.JMenu();
        menuBarLoggaUt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblListaAliens.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblListaAliens.setText("Lista aliens efter plats");

        btnGaTillbaka.setText("Gå tillbaka");
        btnGaTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGaTillbakaMouseClicked(evt);
            }
        });

        tblTabell.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Alien ID", "Namn", "Telefon", "Ras", "Reg. datum"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTabell.setColumnSelectionAllowed(true);
        tblTabell.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTabell);
        tblTabell.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblTabell.getColumnModel().getColumnCount() > 0) {
            tblTabell.getColumnModel().getColumn(0).setHeaderValue("Alien ID");
            tblTabell.getColumnModel().getColumn(1).setHeaderValue("Namn");
            tblTabell.getColumnModel().getColumn(2).setHeaderValue("Telefon");
            tblTabell.getColumnModel().getColumn(3).setHeaderValue("Ras");
            tblTabell.getColumnModel().getColumn(4).setHeaderValue("Reg. datum");
        }

        cmBoxOmrade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmBoxOmradeMouseClicked(evt);
            }
        });

        lblFilterVal.setText("Välj område:");

        lblPlats.setText("Välj plats:");

        jMenu1.setText("Mitt konto");
        menuBar.add(jMenu1);

        jMenu2.setText("Funktioner");

        menuBarAndraLosen.setText("Ändra lösenord");
        menuBarAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarAndraLosenMouseClicked(evt);
            }
        });
        jMenu2.add(menuBarAndraLosen);

        menuBarHanteraAlien.setText("Hantera alien");
        menuBarHanteraAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarHanteraAlienMouseClicked(evt);
            }
        });

        menuBarRegNyAlien.setText("Registrera ny alien");
        menuBarRegNyAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarRegNyAlienMouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(menuBarRegNyAlien);

        jMenuItem2.setText("Uppdatera alien");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(jMenuItem2);

        jMenuItem5.setText("Sök alien");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(jMenuItem5);

        menyBarListaPlats.setText("Lista alien utifrån plats");
        menyBarListaPlats.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menyBarListaPlatsMouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(menyBarListaPlats);

        menuBarListaRas.setText("Lista alien utifrån ras");
        menuBarListaRas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarListaRasMouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(menuBarListaRas);

        menuBarListaDatum.setText("Lista alien efter reg.datum");
        menuBarListaDatum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarListaDatumMouseClicked(evt);
            }
        });
        menuBarHanteraAlien.add(menuBarListaDatum);

        jMenu2.add(menuBarHanteraAlien);

        menuBar.add(jMenu2);

        jMenu5.setText("                                                                                 ");
        menuBar.add(jMenu5);

        menuBarInloggadSom.setText("Inloggad som XXX");
        menuBar.add(menuBarInloggadSom);

        menuBarLoggaUt.setText("Logga ut");
        menuBarLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarLoggaUtMouseClicked(evt);
            }
        });
        menuBar.add(menuBarLoggaUt);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGaTillbaka))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFilterVal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(lblListaAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmBoxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addComponent(lblPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmBoxPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblListaAliens, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmBoxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFilterVal))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlats)
                        .addComponent(cmBoxPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGaTillbaka)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Logga ut högst upp i MenuBar
     * @param evt 
     */
    private void menuBarLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarLoggaUtMouseClicked
        setVisible(false);
        Inloggning inlogg = new Inloggning(idb);
        inlogg.setVisible(true);
    }//GEN-LAST:event_menuBarLoggaUtMouseClicked

    /**
     * Gå tillbaka till föregående sida
     * @param evt 
     */
    private void btnGaTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGaTillbakaMouseClicked
         setVisible(false);
        HanteraAliens hanteraAliens = new HanteraAliens(idb, anvId, anvTyp);
        hanteraAliens.setVisible(true);
    }//GEN-LAST:event_btnGaTillbakaMouseClicked

    /**
     * Körs när användaren valt ett område
     * @param evt 
     */
    private void cmBoxOmradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmBoxOmradeMouseClicked
        getPlatser();
    }//GEN-LAST:event_cmBoxOmradeMouseClicked

    private void menuBarRegNyAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarRegNyAlienMouseClicked
        setVisible(false);
        RegistreraAlien registreraAlien = new RegistreraAlien(idb, anvId, anvTyp);
        registreraAlien.setVisible(true);
    }//GEN-LAST:event_menuBarRegNyAlienMouseClicked

    private void menuBarListaRasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarListaRasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarListaRasMouseClicked

    private void menuBarListaDatumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarListaDatumMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarListaDatumMouseClicked

    private void menuBarHanteraAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarHanteraAlienMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarHanteraAlienMouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void menyBarListaPlatsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menyBarListaPlatsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menyBarListaPlatsMouseClicked

    private void menuBarAndraLosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarAndraLosenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBarAndraLosenMouseClicked

    /**
     * Lägger till alla områden i drop-down-listan
     */
    private void getOmraden() {
        try {
            // Hämta alla områden, spara i hashmap i bokstavsordning
             ArrayList<HashMap<String, String>> listaOmraden = idb.fetchRows("SELECT Benamning FROM omrade ORDER BY Benamning ASC");
             
             // loopa igenom lista och lägg till alla områden i drop down menyn 
               for (int i = 0; i < listaOmraden.size(); i++) {
                   
                String omrade = listaOmraden.get(i).get("Benamning");
                cmBoxOmrade.addItem(omrade);
               }
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }
    
    /**
     * Hämtar platser utifrån vilket område användaren valt
     * och lägger till dom i drop-down-listan
     */
    // TODO Denna metod funkar ej
    private void getPlatser(){
        // Sparar det område som amvändaren valt
        String val = cmBoxOmrade.getSelectedItem().toString();

        try{
            ArrayList<HashMap<String, String>> listaPlatser = idb.fetchRows("SELECT Benamning FROM plats WHERE Finns_I = " + val + " ORDER BY Benamning ASC");
            // loopa igenom lista och lägg till alla områden i drop down menyn 
               for (int i = 0; i < listaPlatser.size(); i++) {
                   
                String plats = listaPlatser.get(i).get("Benamning");
                cmBoxPlats.addItem(plats);
               }
        }catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande:" + e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGaTillbaka;
    private javax.swing.JComboBox<String> cmBoxOmrade;
    private javax.swing.JComboBox<String> cmBoxPlats;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFilterVal;
    private javax.swing.JLabel lblListaAliens;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBarAndraLosen;
    private javax.swing.JMenu menuBarHanteraAlien;
    private javax.swing.JMenu menuBarInloggadSom;
    private javax.swing.JMenuItem menuBarListaDatum;
    private javax.swing.JMenuItem menuBarListaRas;
    private javax.swing.JMenu menuBarLoggaUt;
    private javax.swing.JMenuItem menuBarRegNyAlien;
    private javax.swing.JMenuItem menyBarListaPlats;
    private javax.swing.JTable tblTabell;
    // End of variables declaration//GEN-END:variables
}
