/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

// TODO Lägg till fler val vid registrering beroende på ras. Tex antal armar för Squid
// TODO sätt alienID automatiskt -> räkna uppåt från senaste inlagda (Rosa har nummer 4)

package mib;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author luna
 */
public class RegistreraNyUtrustning extends javax.swing.JFrame {

    // används till konstruktorn
    private InfDB idb;
    private String anvId;
    private String anvTyp;
    private String regID;

    // kontruktor som tar in information som bland annat används till den översta MenuBar
    public RegistreraNyUtrustning(InfDB idb, String anvId, String anvTyp) {
        initComponents();
        this.idb = idb;
        this.anvId = anvId;
        this.anvTyp = anvTyp;
        hamtaUtrustningsID(regID);
        doljText(txtEgenskap);
        doljLabel(lblEgenskap);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitel = new javax.swing.JLabel();
        txtBenamning = new javax.swing.JTextField();
        lblBenamning = new javax.swing.JLabel();
        btnSpara = new javax.swing.JButton();
        lblUtrustningsTyp = new javax.swing.JLabel();
        cmbUtrustningstyp = new javax.swing.JComboBox<>();
        lblConfirm = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblUtrustningID = new javax.swing.JLabel();
        lblUtrustning = new javax.swing.JLabel();
        txtEgenskap = new javax.swing.JTextField();
        lblEgenskap = new javax.swing.JLabel();
        tbValjTyp = new javax.swing.JToggleButton();
        btnTillbaka = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBarStartsida = new javax.swing.JMenu();
        menuBarInget = new javax.swing.JMenu();
        menuBarInloggad = new javax.swing.JMenu();
        menuBarLoggaUt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblTitel.setText("Registrera ny Utrustning");

        lblBenamning.setText("Benämning");

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        lblUtrustningsTyp.setText("Utrustningstyp");

        cmbUtrustningstyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vapen", "Kommunikation", "Teknik", "Okänd" }));
        cmbUtrustningstyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUtrustningstypActionPerformed(evt);
            }
        });

        lblConfirm.setForeground(new java.awt.Color(0, 204, 0));

        jLabel7.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 24)); // NOI18N
        jLabel7.setText("MiB REGISTRERINGSSERVICE");

        lblUtrustningID.setText("UtrustningsID");

        lblUtrustning.setText("ID");

        txtEgenskap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEgenskapActionPerformed(evt);
            }
        });

        lblEgenskap.setText("Egenskap");

        tbValjTyp.setText("Välj typ");
        tbValjTyp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbValjTypMouseClicked(evt);
            }
        });
        tbValjTyp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbValjTypActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Gå tillbaka");
        btnTillbaka.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTillbakaMouseClicked(evt);
            }
        });
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/Vapen.png"))); // NOI18N

        menuBarStartsida.setText("Gå till Startsida");
        menuBarStartsida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarStartsidaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBarStartsida);

        menuBarInget.setText("                                                                                                                          ");
        jMenuBar1.add(menuBarInget);

        menuBarInloggad.setText("Inloggad som Agent");
        jMenuBar1.add(menuBarInloggad);

        menuBarLoggaUt.setText("Logga ut");
        menuBarLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuBarLoggaUtMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuBarLoggaUt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblConfirm))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(lblTitel)))
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBenamning)
                            .addComponent(lblUtrustningID)
                            .addComponent(lblUtrustningsTyp))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(lblUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbUtrustningstyp, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbValjTyp)
                                    .addComponent(txtEgenskap, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSpara, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(lblEgenskap))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblUtrustningID)
                            .addComponent(lblUtrustning))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUtrustningsTyp)
                            .addComponent(cmbUtrustningstyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tbValjTyp)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEgenskap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEgenskap))
                        .addGap(18, 18, 18)
                        .addComponent(btnSpara))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTillbaka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConfirm)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        // Utgår ifrån att det är klicket på sparaknappen som gör att all info sparas i DG
        if (Validering.textFaltHarVarde(txtBenamning) && Validering.comboHarVarde(cmbUtrustningstyp)) {

            String regUtrustningsID = lblUtrustning.getText();
            String regUtrustning = cmbUtrustningstyp.getSelectedItem().toString();
            String regEgenskap = txtEgenskap.getText();

            try {

                if (regUtrustning.equals("Vapen") && Validering.textFaltHarVarde(txtEgenskap)) {
                    laggTill();
                    idb.insert("INSERT INTO Vapen VALUES ('" + regUtrustningsID + "', '" + regEgenskap + "')");
                } else if (regUtrustning.equals("Kommunikation") && Validering.textFaltHarVarde(txtEgenskap)) {
                    laggTill();
                    idb.insert("INSERT INTO Kommunikation VALUES ('" + regUtrustningsID + "', '" + regEgenskap + "')");
                } else if (regUtrustning.equals("Teknik") && Validering.textFaltHarVarde(txtEgenskap)) {
                    laggTill();
                    idb.insert("INSERT INTO Teknik VALUES ('" + regUtrustningsID + "', '" + regEgenskap + "')");
                } else if (regUtrustning.equals("Okänd")) {
                    laggTill();
                } else {
                    JOptionPane.showMessageDialog(null, "Alla fält måste vara ifyllda!");
                }

            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
                System.out.println("Internt felmeddelande" + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Alla fält måste vara ifyllda!");
        }


    }//GEN-LAST:event_btnSparaActionPerformed

    private void hamtaAlienID(String regAlienID) {
        
        try{
            regAlienID = idb.getAutoIncrement("Alien", "Alien_ID");
            lblUtrustning.setText(regAlienID); 
        
        }
        
        catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage()); 
        }
    }
    
    private void laggTill(){
        String regBenamning = txtBenamning.getText();
        String regUtrustningsID = lblUtrustning.getText();
        try{
        
        idb.insert("INSERT INTO Utrustning VALUES ('" + regUtrustningsID + "', '" + regBenamning + "')");
        JOptionPane.showMessageDialog(null, "Ny utrustning är nu registrerad!");
        }
        catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage()); 
        }
        
    }
    
    private void doljText(JTextField textAttDolja){
        textAttDolja.setVisible(false);
    }
    
    private void doljLabel(JLabel labelAttDolja){
        labelAttDolja.setVisible(false);
    }
    
    
    private void txtEgenskapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEgenskapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEgenskapActionPerformed

    private void tbValjTypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbValjTypActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_tbValjTypActionPerformed

    private void tbValjTypMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbValjTypMouseClicked
        String typ = cmbUtrustningstyp.getSelectedItem().toString();
        
        if(typ.equals("Vapen")){
            txtEgenskap.setVisible(true);
            lblEgenskap.setVisible(true);
            lblEgenskap.setText("Kaliber");         
        }
        else if(typ.equals("Kommunikation")){
            txtEgenskap.setVisible(true);
            lblEgenskap.setVisible(true);
            lblEgenskap.setText("Överföringsteknik");
        }
        else if(typ.equals("Teknik")){
            txtEgenskap.setVisible(true);
            lblEgenskap.setVisible(true);
            lblEgenskap.setText("Kraftkälla");
        }
        else{
            doljText(txtEgenskap);
            doljLabel(lblEgenskap);
        }
    }//GEN-LAST:event_tbValjTypMouseClicked

    private void cmbUtrustningstypActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUtrustningstypActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUtrustningstypActionPerformed

    private void menuBarStartsidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarStartsidaMouseClicked
        setVisible(false);
        StartsidaAgent startsidaAgent = new StartsidaAgent(idb, anvId, anvTyp);
        startsidaAgent.setVisible(true);
    }//GEN-LAST:event_menuBarStartsidaMouseClicked

    private void menuBarLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBarLoggaUtMouseClicked
        setVisible(false);
        Inloggning inlogg = new Inloggning(idb);
        inlogg.setVisible(true);
    }//GEN-LAST:event_menuBarLoggaUtMouseClicked

    private void btnTillbakaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTillbakaMouseClicked
        setVisible(false);
        StartsidaAgent startsida = new StartsidaAgent(idb, anvId, anvTyp);
        startsida.setVisible(true);
    }//GEN-LAST:event_btnTillbakaMouseClicked

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void hamtaUtrustningsID(String regID) {
        
        try{
            regID = idb.getAutoIncrement("Utrustning", "Utrustnings_ID");
            lblUtrustning.setText(regID); 
        
        }
        
        catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + e.getMessage()); 
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JToggleButton btnTillbaka;
    private javax.swing.JComboBox<String> cmbUtrustningstyp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblBenamning;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblEgenskap;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblUtrustning;
    private javax.swing.JLabel lblUtrustningID;
    private javax.swing.JLabel lblUtrustningsTyp;
    private javax.swing.JMenu menuBarInget;
    private javax.swing.JMenu menuBarInloggad;
    private javax.swing.JMenu menuBarLoggaUt;
    private javax.swing.JMenu menuBarStartsida;
    private javax.swing.JToggleButton tbValjTyp;
    private javax.swing.JTextField txtBenamning;
    private javax.swing.JTextField txtEgenskap;
    // End of variables declaration//GEN-END:variables
}
