/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author luna
 */
public class SokAgent extends javax.swing.JFrame {

    private InfDB idb;
    private String anvId;
    private String anvTyp;

    /**
     * Creates new form SokAgent
     */
    public SokAgent(InfDB idb, String anvId, String anvTyp) {
        initComponents();
        this.idb = idb;
        this.anvId = anvId;
        this.anvTyp = anvTyp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblAgentID = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblBehorigheter = new javax.swing.JLabel();
        lblBenamning = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();
        txtSoktID = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        lblAnstDatum = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblBenamningSvar = new javax.swing.JLabel();
        lblLosenordSvar = new javax.swing.JLabel();
        lblBehorigheterSvar = new javax.swing.JLabel();
        lblTelefonSvar = new javax.swing.JLabel();
        lblOmradeSvar = new javax.swing.JLabel();
        lblAnsDatSvar = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuStartsida = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuInoggadSom = new javax.swing.JMenu();
        menuLoggaUt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 24)); // NOI18N
        lblRubrik.setText("MiB AGENTSÖK");

        lblAgentID.setText("Agent-ID");

        lblLosenord.setText("Lösenord:");

        lblBehorigheter.setText("Behörigheter:");

        lblBenamning.setText("Benämning:");

        btnSok.setText("SÖK");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        lblTelefon.setText("Telefon:");

        lblAnstDatum.setText("Anställningsdatum:");

        lblOmrade.setText("Område:");

        lblBenamningSvar.setText("-");

        lblLosenordSvar.setText("-");

        lblBehorigheterSvar.setText("-");

        lblTelefonSvar.setText("-");

        lblOmradeSvar.setText("-");

        lblAnsDatSvar.setText("-");

        btnTillbaka.setText("Gå tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        menuStartsida.setText("Tillbaka till startsida");
        menuStartsida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuStartsidaMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuStartsida);

        jMenu2.setText("                                                                                                                                                           ");
        jMenuBar1.add(jMenu2);

        menuInoggadSom.setText("Inloggad som Admin");
        jMenuBar1.add(menuInoggadSom);

        menuLoggaUt.setText("Logga ut");
        menuLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoggaUtMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLoggaUt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSok)
                        .addGap(399, 399, 399))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblBenamning)
                                    .addComponent(lblBehorigheter)
                                    .addComponent(lblTelefon)
                                    .addComponent(lblOmrade)
                                    .addComponent(lblLosenord)
                                    .addComponent(lblAnstDatum))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblBenamningSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblBehorigheterSvar, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(lblLosenordSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblTelefonSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblOmradeSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblAnsDatSvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblAgentID)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSoktID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblRubrik)))
                        .addGap(338, 338, 338))))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnTillbaka)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgentID)
                    .addComponent(txtSoktID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSok)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBenamning)
                    .addComponent(lblBenamningSvar))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefon)
                    .addComponent(lblTelefonSvar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBehorigheter)
                    .addComponent(lblBehorigheterSvar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmrade)
                    .addComponent(lblOmradeSvar))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(lblLosenordSvar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnstDatum)
                    .addComponent(lblAnsDatSvar))
                .addGap(58, 58, 58)
                .addComponent(btnTillbaka)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sökning av egenten utförs
     * @param evt 
     */
    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        // Kollar om användaren fyllt i textfält
        if (Validering.textFaltHarVarde(txtSoktID)) {
            // Kollar om textfält innehåller rätt typ av värde, dvs siffror
            if (Validering.txtFaltHarSiffror(txtSoktID)) {
                try {
                    String soktID = txtSoktID.getText();
                    //Spara alla agentID i lista
                    ArrayList<String> agentnLista = idb.fetchColumn("SELECT agent_ID FROM agent");
                    // Om listan innehåller den sökta agenten körs nedanstående kod
                    if (agentnLista.contains(soktID)) {
                        // Hämta info från databas om den aktuella agenten
                        String agentNamn = idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID = " + soktID + "");
                        String agentTelefon = idb.fetchSingle("SELECT Telefon FROM Agent WHERE Agent_ID = " + soktID + "");
                        String agentBehorighet = idb.fetchSingle("SELECT Administrator FROM Agent WHERE Agent_ID = " + soktID + "");
                        String agentOmrade = idb.fetchSingle("SELECT Benamning FROM Omrade WHERE Omrades_ID IN(SELECT Omrade FROM Agent WHERE Agent_ID = " + soktID + ")");
                        String agentLosenord = idb.fetchSingle("SELECT Losenord FROM Agent WHERE Agent_ID = " + soktID + "");
                        String agentAnsDat = idb.fetchSingle("SELECT Anstallningsdatum FROM Agent WHERE Agent_ID = " + soktID + "");
                        // Skriv ut info om agenten som hittades i databasen
                        lblBenamningSvar.setText(agentNamn);
                        lblTelefonSvar.setText(agentTelefon);
                        lblOmradeSvar.setText(agentOmrade);
                        lblLosenordSvar.setText(agentLosenord);
                        lblAnsDatSvar.setText(agentAnsDat);

                        if (agentBehorighet.contains("J")) {
                            lblBehorigheterSvar.setText("Administratör");
                        } else if (agentBehorighet.contains("N")) {
                            lblBehorigheterSvar.setText("Agentstandard");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "AgentID finns inte!");
                    }
                } catch (InfException e) {
                    JOptionPane.showMessageDialog(null, "Något gick fel!");
                    System.out.println("Internt felmeddelande:" + e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "AlienID måste vara ifyllt!");
        }

    }//GEN-LAST:event_btnSokActionPerformed

    private void menuStartsidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuStartsidaMouseClicked
        setVisible(false);
        StartsidaAdmin startAdm = new StartsidaAdmin(idb, anvId, anvTyp);
        startAdm.setVisible(true);
    }//GEN-LAST:event_menuStartsidaMouseClicked

    private void menuLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoggaUtMouseClicked
        setVisible(false);
        Inloggning inlogg = new Inloggning(idb);
        inlogg.setVisible(true);
    }//GEN-LAST:event_menuLoggaUtMouseClicked

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        setVisible(false);
        AdminHanteraAgenter hantera = new AdminHanteraAgenter(idb, anvId, anvTyp);
        hantera.setVisible(true);
    }//GEN-LAST:event_btnTillbakaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAgentID;
    private javax.swing.JLabel lblAnsDatSvar;
    private javax.swing.JLabel lblAnstDatum;
    private javax.swing.JLabel lblBehorigheter;
    private javax.swing.JLabel lblBehorigheterSvar;
    private javax.swing.JLabel lblBenamning;
    private javax.swing.JLabel lblBenamningSvar;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLosenordSvar;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblOmradeSvar;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonSvar;
    private javax.swing.JMenu menuInoggadSom;
    private javax.swing.JMenu menuLoggaUt;
    private javax.swing.JMenu menuStartsida;
    private javax.swing.JTextField txtSoktID;
    // End of variables declaration//GEN-END:variables
}
