/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mib;

import oru.inf.InfDB;

/**
 *
 * @author luna
 */
public class StartsidaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form StartsidaAgent
     */
    private InfDB idb;
    private String anvId;
    private String anvTyp;

    public StartsidaAdmin(InfDB idb, String anvId, String anvTyp) {
        initComponents();
        this.idb = idb;
        this.anvId = anvId;
        this.anvTyp = anvTyp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminBild = new javax.swing.JLabel();
        lblRubrik = new javax.swing.JLabel();
        btnAndraLosen = new javax.swing.JButton();
        btnAlien = new javax.swing.JButton();
        btnUtrustning = new javax.swing.JButton();
        btnAgenter = new javax.swing.JButton();
        lblHantera = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuInget = new javax.swing.JMenu();
        menuInlogg = new javax.swing.JMenu();
        menuLoggaUt = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAdminBild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Media/admin.png"))); // NOI18N

        lblRubrik.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblRubrik.setText("Välkommen Administratör!");

        btnAndraLosen.setText("Ändra lösenord");
        btnAndraLosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAndraLosenMouseClicked(evt);
            }
        });

        btnAlien.setText("Aliens");
        btnAlien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlienMouseClicked(evt);
            }
        });

        btnUtrustning.setText("Utrustning");
        btnUtrustning.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUtrustningMouseClicked(evt);
            }
        });

        btnAgenter.setText("Agenter");
        btnAgenter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgenterActionPerformed(evt);
            }
        });

        lblHantera.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblHantera.setText("Hantera ...");

        menuInget.setText("                                                                                                                                                                                                        ");
        jMenuBar1.add(menuInget);

        menuInlogg.setText("Inloggad som Admin");
        jMenuBar1.add(menuInlogg);

        menuLoggaUt.setText("Logga ut");
        menuLoggaUt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLoggaUtMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuLoggaUt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAndraLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminBild, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHantera)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAgenter, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(78, 78, 78))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnAndraLosen)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(lblHantera)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnAlien, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(lblAdminBild, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(104, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgenterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgenterActionPerformed
        setVisible(false);
        AdminHanteraAgenter adminHanteraAgenter = new AdminHanteraAgenter(idb, anvId, anvTyp);
        adminHanteraAgenter.setVisible(true);    }//GEN-LAST:event_btnAgenterActionPerformed

    private void btnAlienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlienMouseClicked
        setVisible(false);
        HanteraAliensAdmin adminHanteraAlien = new HanteraAliensAdmin(idb, anvId, anvTyp);
        adminHanteraAlien.setVisible(true);
    }//GEN-LAST:event_btnAlienMouseClicked

    private void btnAndraLosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAndraLosenMouseClicked
        setVisible(false);
        AndraLosenord andraLosenord = new AndraLosenord(idb, anvId, anvTyp);
        andraLosenord.setVisible(true);
    }//GEN-LAST:event_btnAndraLosenMouseClicked

    private void btnUtrustningMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUtrustningMouseClicked
        setVisible(false);
        HanteraUtrustningAdmin hantera = new HanteraUtrustningAdmin(idb, anvId, anvTyp);
        hantera.setVisible(true);
    }//GEN-LAST:event_btnUtrustningMouseClicked

    private void menuLoggaUtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLoggaUtMouseClicked
        setVisible(false);
        Inloggning inlogg = new Inloggning(idb);
        inlogg.setVisible(true);
    }//GEN-LAST:event_menuLoggaUtMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenter;
    private javax.swing.JButton btnAlien;
    private javax.swing.JButton btnAndraLosen;
    private javax.swing.JButton btnUtrustning;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblAdminBild;
    private javax.swing.JLabel lblHantera;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JMenu menuInget;
    private javax.swing.JMenu menuInlogg;
    private javax.swing.JMenu menuLoggaUt;
    // End of variables declaration//GEN-END:variables
}
